export const universities = [
  {
    name: "Northbridge International University",
    slug: "northbridge-international-university",
    country: "Canada",
    city: "Toronto",
    type: "Public",
    level: "Undergraduate",
    course: "Computer Science",
    tuition: 24500,
    tuitionLabel: "CAD 24,500/yr",
    ranking: "#38 National",
    rating: 4.8,
    reviews: 312,
    intake: "September 2026",
    scholarship: "Up to 30%",
    duration: "4 years",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=85",
    summary: "A career-focused campus with strong co-op routes, research labs, and international student support.",
    highlights: ["Co-op programs", "STEM focused", "Post-study work support"],
  },
  {
    name: "Westhaven Medical University",
    slug: "westhaven-medical-university",
    country: "United Kingdom",
    city: "Manchester",
    type: "Private",
    level: "Undergraduate",
    course: "MBBS",
    tuition: 18500,
    tuitionLabel: "GBP 18,500/yr",
    ranking: "#22 Medical",
    rating: 4.7,
    reviews: 226,
    intake: "January 2027",
    scholarship: "Merit grants",
    duration: "5 years",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=85",
    summary: "A medical pathway university with clinical exposure, simulation labs, and guided licensing prep.",
    highlights: ["Clinical rotations", "English medium", "Licensing guidance"],
  },
  {
    name: "Pacific Tech Institute",
    slug: "pacific-tech-institute",
    country: "Australia",
    city: "Melbourne",
    type: "Public",
    level: "Postgraduate",
    course: "Data Analytics",
    tuition: 31500,
    tuitionLabel: "AUD 31,500/yr",
    ranking: "#15 Innovation",
    rating: 4.9,
    reviews: 411,
    intake: "July 2027",
    scholarship: "Up to 25%",
    duration: "2 years",
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=1200&q=85",
    summary: "A modern technology institute known for applied learning, industry projects, and startup mentoring.",
    highlights: ["Industry projects", "Startup hub", "High employability"],
  },
  {
    name: "Europa Business School",
    slug: "europa-business-school",
    country: "Germany",
    city: "Berlin",
    type: "Private",
    level: "Postgraduate",
    course: "MBA",
    tuition: 19800,
    tuitionLabel: "EUR 19,800/yr",
    ranking: "#12 Business",
    rating: 4.6,
    reviews: 184,
    intake: "October 2026",
    scholarship: "Early applicant awards",
    duration: "18 months",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=85",
    summary: "A practical business school with global faculty, consulting projects, and entrepreneurship tracks.",
    highlights: ["Global faculty", "Consulting projects", "EU career support"],
  },
  {
    name: "Maple Leaf College",
    slug: "maple-leaf-college",
    country: "Canada",
    city: "Vancouver",
    type: "Community College",
    level: "Diploma",
    course: "Hospitality Management",
    tuition: 16800,
    tuitionLabel: "CAD 16,800/yr",
    ranking: "Top 50 College",
    rating: 4.5,
    reviews: 143,
    intake: "May 2027",
    scholarship: "Need-based aid",
    duration: "2 years",
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=1200&q=85",
    summary: "A hands-on college for students seeking affordable diploma pathways and paid internship options.",
    highlights: ["Paid internship", "Affordable fees", "Pathway transfers"],
  },
  {
    name: "Asian Global University",
    slug: "asian-global-university",
    country: "Singapore",
    city: "Singapore",
    type: "Private",
    level: "Undergraduate",
    course: "Business Analytics",
    tuition: 28500,
    tuitionLabel: "SGD 28,500/yr",
    ranking: "#9 Asia Emerging",
    rating: 4.8,
    reviews: 267,
    intake: "August 2027",
    scholarship: "Up to 20%",
    duration: "3 years",
    image: "https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?auto=format&fit=crop&w=1200&q=85",
    summary: "A city campus with strong analytics programs, employer networks, and Asia-Pacific exposure.",
    highlights: ["City campus", "Employer network", "Analytics lab"],
  },
];

export const universityCountries = [...new Set(universities.map((item) => item.country))];
export const universityCourses = [...new Set(universities.map((item) => item.course))];
export const universityTypes = [...new Set(universities.map((item) => item.type))];
