export const heroSlides = [
  {
    title: "Your Global Move Starts Here",
    subtitle:
      "From visas and study abroad guidance to relocation and documentation, Immify helps you plan every step with confidence.",
    image: "/images/home/home-hero-immigration.png",
    badge: "Trusted by aspiring global movers",
  },
  {
    title: "Immigration Guidance Made Simple",
    subtitle:
      "Explore PR pathways, skilled migration options, family sponsorship, and immigration consultations in one place.",
    image: "/images/home/home-hero-documentation.png",
    badge: "Expert-led support",
  },
  {
    title: "Study Abroad, Work Abroad, Settle Abroad",
    subtitle:
      "Get help with admissions, test prep, relocation, and documentation for a smoother transition abroad.",
    image: "/images/home/home-hero-study.png",
    badge: "End-to-end assistance",
  },
  {
    title: "Build Your Career Beyond Borders",
    subtitle:
      "Connect with trusted experts for work visas, global opportunities, and smooth relocation support.",
    image: "/images/home/home-hero-work.png",
    badge: "Career migration support",
  },
];

export const serviceCategories = [
  {
    slug: "immigration-services",
    name: "Immigration Services",
    shortDescription: "Full immigration case support and assessment",
    image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80",
    services: [
      "Permanent Residency (PR)",
      "Express Entry",
      "Provincial Nominee Program (PNP)",
      "Skilled Migration",
      "Skilled Independent Visa",
      "Skilled Nominated Visa",
      "Family Sponsorship",
      "Spouse Sponsorship",
      "Parent Sponsorship",
      "Child Sponsorship",
      "Citizenship Application",
      "Naturalization",
      "Residency Renewal",
      "Residency Extension",
      "Immigration Appeals",
      "Immigration Consultation",
      "Immigration Documentation",
      "Immigration Case Management",
      "Immigration Eligibility Assessment",
      "Immigration Profile Creation",
    ],
  },
  {
    slug: "visa-services",
    name: "Visa Services",
    shortDescription: "Tourist, work, student, business, dependent and transit visas",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764b5b?auto=format&fit=crop&w=900&q=80",
    services: [
      // Tourist & Visit
      "Tourist Visa",
      "Visit Visa",
      "Family Visit Visa",
      "Friends Visit Visa",
      "Short Stay Visa",
      "Long Stay Visa",
      "Multiple Entry Visa",
      "Single Entry Visa",
      // Work
      "Work Permit",
      "Employment Visa",
      "Skilled Worker Visa",
      "Temporary Work Visa",
      "Seasonal Worker Visa",
      "Intra-Company Transfer Visa",
      "ICT Visa",
      "Digital Nomad Visa",
      "Remote Work Visa",
      "Freelancer Visa",
      "Job Seeker Visa",
      // Student
      "Student Visa",
      "Study Permit",
      "Exchange Program Visa",
      "Research Visa",
      "Internship Visa",
      "Graduate Visa",
      "Post Study Work Visa",
      // Business
      "Business Visa",
      "Investor Visa",
      "Startup Visa",
      "Entrepreneur Visa",
      "Self Employment Visa",
      "Golden Visa",
      "Innovator Visa",
      // Dependent
      "Spouse Visa",
      "Partner Visa",
      "Child Dependent Visa",
      "Parent Dependent Visa",
      // Transit
      "Airport Transit Visa",
      "Transit Permit",
    ],
  },
  {
    slug: "study-abroad-services",
    name: "Study Abroad Services",
    shortDescription: "Admissions, scholarships, pre-departure and visa support",
    image: "https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=900&q=80",
    services: [
      "University Admission",
      "College Admission",
      "School Admission",
      "Course Selection",
      "Country Selection",
      "Career Counselling",
      "University Shortlisting",
      "SOP Writing",
      "LOR Preparation",
      "Resume Preparation",
      "Admission Application",
      "Scholarship Assistance",
      "Education Loan Assistance",
      "Accommodation Assistance",
      "Visa Filing",
      "CAS Assistance",
      "Offer Letter Assistance",
      "Tuition Fee Payment Guidance",
      "Pre Departure Guidance",
      "Student Insurance",
      "Forex Assistance",
    ],
  },
  {
    slug: "test-preparation",
    name: "Test Preparation",
    shortDescription: "Exam coaching and registrations",
    image: "https://images.unsplash.com/photo-1515165562835-c8d2a5f6f9a6?auto=format&fit=crop&w=900&q=80",
    services: [
      "IELTS Coaching",
      "IELTS Registration",
      "PTE Coaching",
      "TOEFL Coaching",
      "GRE Coaching",
      "GMAT Coaching",
      "SAT Coaching",
      "ACT Coaching",
      "Duolingo English Test",
      "CELPIP Coaching",
      "OET Coaching",
      "German Language Training",
      "French Language Training",
      "Japanese Language Training",
    ],
  },
  {
    slug: "career-employment-services",
    name: "Career & Employment Services",
    shortDescription: "Job search, CVs and employer connections",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=80",
    services: [
      "International Job Search",
      "Overseas Recruitment",
      "Resume Writing",
      "CV Optimization",
      "LinkedIn Profile Optimization",
      "Job Application Support",
      "Interview Preparation",
      "Mock Interviews",
      "Employer Sponsorship Assistance",
      "Skill Assessment",
      "Credential Evaluation",
      "WES Evaluation",
      "ECA Assistance",
      "Professional Licensing",
    ],
  },
  {
    slug: "family-relocation-services",
    name: "Family Relocation Services",
    shortDescription: "Before and after arrival family relocation support",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=900&q=80",
    services: [
      // Before Departure
      "Relocation Planning",
      "Country Orientation",
      "Cost of Living Guidance",
      "Document Verification",
      "Visa Documentation",
      "Travel Planning",
      // After Arrival
      "Airport Pickup",
      "Temporary Accommodation",
      "Permanent Accommodation Search",
      "House Rental Assistance",
      "Utility Connection",
      "SIM Card Assistance",
      "Bank Account Opening",
      "Tax Registration",
      "Social Security Registration",
      "Health Insurance",
      "Medical Registration",
      "Driving License Assistance",
      "Local Transportation Guidance",
      // Family Relocation
      "School Admission Assistance",
      "Child Care Assistance",
      "Family Settlement",
      "Spouse Employment Guidance",
      "Local Community Support",
    ],
  },
  {
    slug: "documentation-services",
    name: "Documentation Services",
    shortDescription: "Passport, attestations, PCC and translations",
    image: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=900&q=80",
    services: [
      "Passport Renewal",
      "Passport Assistance",
      "PCC (Police Clearance Certificate)",
      "Birth Certificate Assistance",
      "Marriage Certificate Assistance",
      "Affidavit Preparation",
      "Notary Services",
      "Apostille Services",
      "Document Attestation",
      "Embassy Attestation",
      "MOFA Attestation",
      "Translation Services",
      "Certified Translation",
      "Medical Examination Guidance",
      "Biometrics Appointment",
      "Visa Appointment Booking",
    ],
  },
  {
    slug: "financial-services",
    name: "Financial Services",
    shortDescription: "Loans, forex and money transfer services",
    image: "https://images.unsplash.com/photo-1542223616-7d37b4b23f31?auto=format&fit=crop&w=900&q=80",
    services: [
      "Education Loan",
      "Personal Loan for Immigration",
      "Forex Services",
      "International Money Transfer",
      "Blocked Account Assistance",
      "GIC Account Assistance",
      "Proof of Funds Guidance",
      "Tax Consultation",
    ],
  },
  {
    slug: "business-setup-immigration",
    name: "Business Set Up & Immigration Services",
    shortDescription: "Company registration and investor visas",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80",
    services: [
      "Company Registration Abroad",
      "Overseas Business Setup",
      "Business Expansion",
      "Business Incorporation",
      "Corporate Immigration",
      "Startup Visa Consultancy",
      "Franchise Setup",
      "Investor Consultation",
    ],
  },
  {
    slug: "healthcare-insurance",
    name: "Healthcare & Insurance Services",
    shortDescription: "Medical insurance and health services",
    image: "https://images.unsplash.com/photo-1587500153262-8b89b9f4f6d5?auto=format&fit=crop&w=900&q=80",
    services: [
      "Overseas Medical Insurance",
      "Student Insurance",
      "Travel Insurance",
      "Health Card Registration",
      "Medical Fitness Guidance",
    ],
  },
  {
    slug: "legal-compliance-services",
    name: "Legal & Compliance Services",
    shortDescription: "Lawyers, appeals, deportation support and litigation",
    image: "https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=900&q=80",
    services: [
      "Immigration Lawyer Consultation",
      "Visa Refusal Assistance",
      "Appeal Filing",
      "Legal Documentation",
      "Compliance Consultation",
      "Case Review",
      "Deportation Support",
      "Immigration Litigation",
    ],
  },
];

export const premiumServiceItems = [
  {
    slug: "work-visa",
    title: "Work Visa",
    description: "Secure your future with the right work visa for your career goals.",
    icon: "🛂",
    detailBody:
      "Our work visa support covers profile review, eligibility checks, sponsor documentation, and filing strategy to improve approval confidence.",
    benefits: ["Eligibility assessment", "Employer sponsor support", "Application filing", "Interview preparation"],
  },
  {
    slug: "study-visa",
    title: "Study Visa",
    description: "Study in top countries with expert guidance and end-to-end support.",
    icon: "🎓",
    detailBody:
      "From university shortlisting to visa interview guidance, we provide complete support for students planning overseas education.",
    benefits: ["Course and country selection", "Offer and CAS support", "Financial document review", "Visa interview coaching"],
  },
  {
    slug: "family-sponsorship",
    title: "Family Sponsorship",
    description: "Reunite with your loved ones. We make the process seamless.",
    icon: "👨‍👩‍👧",
    detailBody:
      "We help families manage eligibility, documentation, and legal compliance for smoother sponsorship applications.",
    benefits: ["Relationship proof guidance", "Document checklist", "Timeline planning", "Case follow-up"],
  },
  {
    slug: "permanent-residency",
    title: "Permanent Residency",
    description: "Build a stable future with permanent residency options.",
    icon: "📈",
    detailBody:
      "Our PR consultants provide pathway comparison, score optimization, and profile management for major destination countries.",
    benefits: ["Pathway comparison", "Score improvement strategy", "Profile creation", "PR documentation"],
  },
  {
    slug: "visitor-visa",
    title: "Visitor Visa",
    description: "Visit your family, explore new opportunities, and create memories.",
    icon: "✈️",
    detailBody:
      "We prepare complete visitor visa files with purpose letters, itinerary support, and financial documentation review.",
    benefits: ["Travel purpose documentation", "Itinerary support", "Financial proof guidance", "Application submission"],
  },
  {
    slug: "canada-immigration",
    title: "Canada Immigration",
    description: "Expert guidance for a smooth immigration journey to Canada.",
    icon: "🍁",
    detailBody:
      "Get specialized support for Express Entry, PNP, and family routes with end-to-end Canada-focused case management.",
    benefits: ["Express Entry profile", "PNP matching", "CRS strategy", "Post-ITA support"],
  },
  {
    slug: "citizenship-services",
    title: "Citizenship Services",
    description: "Achieve your dream of citizenship with confidence and ease.",
    icon: "📄",
    detailBody:
      "Citizenship filing assistance includes residency calculations, legal checklist verification, and application packaging.",
    benefits: ["Residency timeline review", "Document verification", "Application packaging", "Interview readiness"],
  },
  {
    slug: "consultation",
    title: "Consultation",
    description: "Get personalized advice from our immigration experts.",
    icon: "🎧",
    detailBody:
      "Book one-on-one expert sessions to evaluate goals, compare pathways, and get a personalized action roadmap.",
    benefits: ["One-on-one strategy", "Country comparison", "Risk review", "Action plan"],
  },
];

export const topCountries = [
  {
    slug: "canada",
    name: "Canada",
    image: "https://flagcdn.com/w320/ca.png",
    summary: "Skilled migration, PR visas and work opportunities.",
    programs: ["Canada Express Entry", "Canada PNP", "Canada Atlantic Immigration Program"],
  },
  {
    slug: "australia",
    name: "Australia",
    image: "https://flagcdn.com/w320/au.png",
    summary: "Work, study and migrate to a prosperous future.",
    programs: ["Australia Skilled Migration", "Australia PR"],
  },
  {
    slug: "united-states",
    name: "United States",
    image: "https://flagcdn.com/w320/us.png",
    summary: "Explore work, study and settlement options.",
    programs: ["USA H-1B Visa", "USA L-1 Visa", "USA EB-2 / EB-3 Immigration"],
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    image: "https://flagcdn.com/w320/gb.png",
    summary: "Study in top universities and build your career.",
    programs: ["UK Skilled Worker Visa", "UK Graduate Route"],
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    image: "https://flagcdn.com/w320/nz.png",
    summary: "Live, work and settle in a peaceful environment.",
    programs: ["New Zealand Skilled Migrant Category"],
  },
  {
    slug: "germany",
    name: "Germany",
    image: "https://flagcdn.com/w320/de.png",
    summary: "Job seeker visa, work and PR opportunities.",
    programs: ["Germany Opportunity Card", "Germany Job Seeker Visa"],
  },
  {
    slug: "uae",
    name: "UAE",
    image: "https://flagcdn.com/w320/ae.png",
    summary: "Explore career and business opportunities.",
    programs: ["UAE Employment Visa", "UAE Golden Visa"],
  },
  {
    slug: "singapore",
    name: "Singapore",
    image: "https://flagcdn.com/w320/sg.png",
    summary: "Work opportunities in a global business hub.",
    programs: ["Singapore Employment Pass"],
  },
  {
    slug: "ireland",
    name: "Ireland",
    image: "https://flagcdn.com/w320/ie.png",
    summary: "Study, work and settle in a growing economy.",
    programs: ["Ireland Critical Skills Employment Permit"],
  },
  {
    slug: "france",
    name: "France",
    image: "https://flagcdn.com/w320/fr.png",
    summary: "Study in France and build a bright future.",
    programs: ["France Talent Passport", "France Student Visa"],
  },
];

export const topCities = [
  {
    slug: "new-delhi",
    name: "New Delhi",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=900&q=80",
    summary: "Embassies, visa offices, and premium consultant access.",
    highlights: ["Embassy processes", "PR experts", "Legal advisors"],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=900&q=80",
    summary: "Corporate immigration, overseas recruitment, and legal support.",
    highlights: ["Corporate visas", "Recruitment support", "Business immigration"],
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=900&q=80",
    summary: "Tech-focused work visa and relocation guidance services.",
    highlights: ["Tech work permits", "Dependent visas", "Relocation planning"],
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    image: "https://images.unsplash.com/photo-1622308644420-b20142dc993c?auto=format&fit=crop&w=900&q=80",
    summary: "Education, PR consulting, and documentation specialists.",
    highlights: ["Student migration", "PR counseling", "Document support"],
  },
  {
    slug: "chennai",
    name: "Chennai",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=900&q=80",
    summary: "Study abroad and skilled migration consultant network.",
    highlights: ["Study abroad", "Skilled migration", "Language prep"],
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=900&q=80",
    summary: "Visa filing support, legal review, and travel compliance.",
    highlights: ["Visa filing", "Compliance", "Travel documentation"],
  },
  {
    slug: "pune",
    name: "Pune",
    image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=900&q=80",
    summary: "Student mobility and career migration counseling hubs.",
    highlights: ["Career migration", "Student mobility", "Interview prep"],
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=900&q=80",
    summary: "Business visas, investor pathways, and settlement support.",
    highlights: ["Investor routes", "Business setup", "Settlement support"],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    image: "/images/cities/jaipur.svg",
    summary: "Affordable visa assistance and document advisory options.",
    highlights: ["Visa advisory", "Affordable counseling", "Document review"],
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    image: "/images/cities/lucknow.svg",
    summary: "Growing network of immigration and relocation services.",
    highlights: ["Consultant network", "Relocation assistance", "Application guidance"],
  },
];

export const vendorCategories = [
  {
    slug: "immigration-consultants",
    title: "Immigration Consultants",
    summary: "Experts guiding visa and residence applications.",
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
    tags: ["PR", "Visa", "Consultation"],
  },
  {
    slug: "visa-consultants",
    title: "Visa Consultants",
    summary: "Specialists for tourist, work, student, and family visa cases.",
    image:
      "https://images.unsplash.com/photo-1577563908411-5077b6dc7624?auto=format&fit=crop&w=900&q=80",
    tags: ["Work Visa", "Study Visa", "Dependant Visa"],
  },
  {
    slug: "study-abroad-consultants",
    title: "Study Abroad Consultants",
    summary: "Support for admissions, scholarships, and course planning.",
    image:
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80",
    tags: ["University", "SOP", "Scholarship"],
  },
  {
    slug: "language-training-institutes",
    title: "Language Training Institutes",
    summary: "IELTS, PTE, TOEFL, and language coaching services.",
    image:
      "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80",
    tags: ["IELTS", "PTE", "English Training"],
  },
  {
    slug: "overseas-education-consultants",
    title: "Overseas Education Consultants",
    summary: "Dedicated counseling for global admissions and study destinations.",
    image:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80",
    tags: ["Admissions", "Counseling", "Universities"],
  },
  {
    slug: "overseas-recruitment-agencies",
    title: "Overseas Recruitment Agencies",
    summary: "Agencies connecting candidates with international employers.",
    image:
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80",
    tags: ["Jobs Abroad", "Recruitment", "Employers"],
  },
  {
    slug: "relocation-settlement-service-providers",
    title: "Relocation & Settlement Service Providers",
    summary: "Move-in support from arrival to local setup and housing.",
    image:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80",
    tags: ["Relocation", "Housing", "Arrival"],
  },
  {
    slug: "immigration-lawyers-legal-advisors",
    title: "Immigration Lawyers & Legal Advisors",
    summary: "Legal experts for appeals, complex cases, and compliance.",
    image:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=900&q=80",
    tags: ["Legal", "Appeals", "Compliance"],
  },
  {
    slug: "documentation-attestation-agencies",
    title: "Documentation & Attestation Agencies",
    summary: "Specialists for document prep, notarization, and attestations.",
    image:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    tags: ["Attestation", "Notary", "Documentation"],
  },
  {
    slug: "travel-medical-insurance-providers",
    title: "Travel & Medical Insurance Providers",
    summary: "Coverage plans for travel, study, and relocation safety.",
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80",
    tags: ["Insurance", "Travel", "Medical"],
  },
  {
    slug: "education-loan-financial-assistance-providers",
    title: "Education Loan & Financial Assistance Providers",
    summary: "Funding support for tuition, relocation, and study expenses.",
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80",
    tags: ["Loans", "Education Finance", "Funding"],
  },
  {
    slug: "foreign-exchange-forex-service-providers",
    title: "Foreign Exchange (Forex) Service Providers",
    summary: "Competitive exchange, remittance, and currency solutions.",
    image:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=80",
    tags: ["Forex", "Remittance", "Currency"],
  },
  {
    slug: "translation-interpretation-services",
    title: "Translation & Interpretation Services",
    summary: "Certified translations and interpretation for official processes.",
    image:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80",
    tags: ["Translation", "Interpretation", "Certified"],
  },
  {
    slug: "international-tax-compliance-advisors",
    title: "International Tax & Compliance Advisors",
    summary: "Cross-border tax planning and regulatory guidance.",
    image:
      "https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=900&q=80",
    tags: ["Tax", "Compliance", "Advisory"],
  },
  {
    slug: "accommodation-housing-assistance-providers",
    title: "Accommodation & Housing Assistance Providers",
    summary: "Student and family housing support near destination cities.",
    image:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80",
    tags: ["Accommodation", "Housing", "Rentals"],
  },
];

export const marketplaceTabs = [
  {
    slug: "immigration-services",
    name: "Immigration Services",
    shortLabel: "IM",
    services: ["PR", "Express Entry", "Citizenship", "Residency"],
  },
  {
    slug: "visa-services",
    name: "Visa Services",
    shortLabel: "VS",
    services: ["Tourist Visa", "Work Visa", "Student Visa", "Business Visa", "Dependent Visa"],
  },
  {
    slug: "study-abroad-services",
    name: "Study Abroad Services",
    shortLabel: "SA",
    services: ["University Services", "School Addmission"],
  },
  {
    slug: "test-prepation",
    name: "Test Prepation",
    shortLabel: "TP",
    services: ["IELTS", "TOEFL", "GRE", "SAT", "GMAT", "Language Training"],
  },
  {
    slug: "international-services",
    name: "International Services",
    shortLabel: "IS",
    services: ["Global Mobility", "Destination Planning", "Cross Border Support", "Settlement Guidance"],
  },
  {
    slug: "family-relocation-services",
    name: "Family Relocation Services",
    shortLabel: "FR",
    services: ["Family Move Planning", "School Support", "Housing Assistance", "Arrival Support"],
  },
  {
    slug: "document-attention-services",
    name: "Document Attention Services",
    shortLabel: "DA",
    services: ["Attestation", "Notary", "Translation", "Apostille"],
  },
  {
    slug: "financial-services",
    name: "Financial Services",
    shortLabel: "FS",
    services: ["Education Loan", "Funds Guidance", "International Transfers", "Tax Advisory"],
  },
  {
    slug: "business-setup-services-and-immigration",
    name: "Business Setup Services and Immigration",
    shortLabel: "BS",
    services: ["Company Setup", "Investor Pathways", "Startup Visa", "Corporate Immigration"],
  },
  {
    slug: "helth-insurance",
    name: "Helth Insurance",
    shortLabel: "HI",
    services: ["Travel Insurance", "Student Insurance", "Medical Coverage", "Family Coverage"],
  },
  {
    slug: "forex-services",
    name: "Forex Services",
    shortLabel: "FX",
    services: ["Currency Exchange", "Remittance", "Rate Lock", "Forex Card"],
  },
  {
    slug: "legal-and-complance",
    name: "Legal and Complance",
    shortLabel: "LC",
    services: ["Legal Review", "Appeal Support", "Case Compliance", "Policy Guidance"],
  },
];
